# Assignment 9 : Numpy

## Task 1 : Creating Numpy Arrays

In [2]:
# Import numpy
import numpy as np

# Create 1D Array from 1 to 10
oneDarray=np.arange(1,11)

# Create 2D array of shape(3,3) values from 1 to 9
twoDarray=np.arange(1,10).reshape(3,3)

# Create numpy array from list
numpy_array=np.arange(10,51,10)


In [19]:
# Print
print(oneDarray)
print(oneDarray.shape)
print(oneDarray.dtype)
print()
print(twoDarray)
print(twoDarray.shape)
print(twoDarray.dtype)
print()
print(numpy_array)
print(numpy_array.shape)
print(numpy_array.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
int64

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64

[10 20 30 40 50]
(5,)
int64


In [4]:
# Print data types
print(oneDarray.dtype)
print(twoDarray.dtype)
print(numpy_array.dtype)

int64
int64
int64


## Task 2: Important Mathematical Operations

In [5]:
# Given arrays
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])


# Apply operations and print
print("Addition of A and B:", A+B)
print("Subtraction of A and B:", A-B)
print("Multiplication of A and B:", A*B)
print("Division of A and B:",A/B)
print("Power of A:", A**2)

Addition of A and B: [11 22 33 44]
Subtraction of A and B: [ 9 18 27 36]
Multiplication of A and B: [ 10  40  90 160]
Division of A and B: [10. 10. 10. 10.]
Power of A: [ 100  400  900 1600]


# Task 3: Important Numpy Mathematical Formulas

In [6]:
# Given
values=np.array([2,4,6,8,10])

# Calculate:

## Square root
square_value=np.sqrt(values)

## Exponential
expo_value=np.exp(values)

## logarithm
log_value=np.log(values)

## Sum  of elements
sum_value=np.sum(values)

## Cumulative sum of elements
cum_value=np.cumsum(values)



# Print:

print("Square root of each element:",square_value,"\n")
print("Exponential of each element:",expo_value,"\n")
print("Natural logarithmm of each element:",log_value,"\n")
print("Sum of all Elements:",sum_value,"\n")
print("Cumulative sum of element:",cum_value)


Square root of each element: [1.41421356 2.         2.44948974 2.82842712 3.16227766] 

Exponential of each element: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04] 

Natural logarithmm of each element: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509] 

Sum of all Elements: 30 

Cumulative sum of element: [ 2  6 12 20 30]


## Task 4: Aggregation Operations

In [7]:
# Given
data = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

# Find:

## Row wise sum
row_wise=np.sum(data,axis=1)

## Column wise sum
col_wise=np.sum(data,axis=0)

## Minimium value
min_value=np.min(data)

## Maximium value
max_value=np.max(data)

## mean
mean_value=np.mean(data)


In [8]:
# Print
print("Row wise Sum:",row_wise)
print("Column wise Sum:",col_wise)
print("Minimum Value:",min_value)
print("Maximum Value:",max_value)
print("Mean Value:",mean_value)


Row wise Sum: [ 60 150 240]
Column wise Sum: [120 150 180]
Minimum Value: 10
Maximum Value: 90
Mean Value: 50.0


# Task 5: Statistical Operations (Core Focus)

In [9]:
# Given 
marks=np.array([78,85,90,66,72,88,95,60])

# Calculate

## Mean Value
mean_mark = np.mean(marks)

## Median Value
median_mark = np.median(marks)

## Variance
var_mark = np.var(marks)

## Standard Deviation
std_mark = np.std(marks)

## Minimum & Maximum
min_mark = np.min(marks)
max_mark = np.max(marks)

## Range between min - max marks
range_mark = max_mark - min_mark

In [10]:
# Print
print("Mean Mark:",mean_mark)
print("Median Mark:",median_mark)
print("Variance:",var_mark)
print("Standard Deviation:",std_mark)
print(f"Minimum Mark: {min_mark}","&",f"Maximum Mark: {max_mark}")
print("Range Marks:",range_mark)

Mean Mark: 79.25
Median Mark: 81.5
Variance: 134.1875
Standard Deviation: 11.583932838203095
Minimum Mark: 60 & Maximum Mark: 95
Range Marks: 35


# Task 6: Percentiles & Sorting

In [11]:
## Given
marks=np.array([78,85,90,66,72,88,95,60])

# 1. Sort the array
sorted_marks=np.sort(marks)
print("Sorted Marks:",sorted_marks)


# 2. find:
## 25th percentile
print("25th Percentile:",np.percentile(marks,25))
## 50th percentile
print("50th Percentile:",np.percentile(marks,50))
## 75th percentile
print("75th Percentile:",np.percentile(marks,75))


# 3. Count the students scored above the above marks
average=np.mean(marks)
count=np.sum(marks>average)

print("Average Marks:",average)
print("Students Above Average:",count)

Sorted Marks: [60 66 72 78 85 88 90 95]
25th Percentile: 70.5
50th Percentile: 81.5
75th Percentile: 88.5
Average Marks: 79.25
Students Above Average: 4


# Task 7: Mini Use Case : Sales Analysis

In [12]:
# Given daily sales data
sales=np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

# Perform:
## Total weekly sales
total_sales=np.sum(sales)

## Average daily sales
average_sales=np.mean(sales)

## Highest & Lowest sales day
high_sales=np.max(sales)
low_sales=np.min(sales)

## Standard Devitaion
std_sales=np.std(sales)

## Identify days where sales were above average
above_avg=np.where(sales>average_sales)[0]+1  # +1 because days starts from 1


In [13]:
# Print Perform:
print("Total weekly sales:",total_sales)
print("Average daily Sales:",average_sales)
print(f"Highest sale day: {high_sales}","&",f"Lowest sale day: {low_sales}")
print("Standard deviation of sales:",std_sales)
print("Days With Sales above Average:",above_avg)

Total weekly sales: 10700
Average daily Sales: 1528.5714285714287
Highest sale day: 2000 & Lowest sale day: 900
Standard deviation of sales: 345.2298849598449
Days With Sales above Average: [4 5 6 7]
